### ISSUE TITLE
abnormal message stopped my script: "fusion_filter.txt is empty,no fusion exists"

### ISSUE THREAD

**Issue by lva85** [bm2-lab/neoFusion#2]
Hi, authors,
I just ran your docker image and performed the "neofusion" program, after giving the parameters, then quickly stopped and en message occurred, please help to identify the reasons. Thank you very much!
my script:
python /usr/local/neoFusion.py midway --fusion test.fa --hla HLA-A02:01

message:
######## Running  netMHCpan  #############
fusion_filter.txt is empty,no fusion exists

**Comment by weizhiting** [comment]
Hi! please provide fusion proteins in fa format. I have updated the readme for preventing misunderstanding. What is more, an example fusion protein has been uploaded, you should run it successfully.
